FILE_NAME = 'Leduc_A.txt'
SOLVER_TIME_STEPS = 10000
REFINER_TIME_STEPS = 1000

ABSTRACTION_PERCENTAGE = 0.65
WIZARD_COEFFICIENT = 2
PERFORM_ABSTRACTION = True
COMPRESS_PLAYER_2 = False
PERFORM_REFINEMENT = False
PRINT_BOTH_STRATEGIES = False
