FILE_NAME = 'leduc_C.txt'
SOLVER_TIME_STEPS = 1000000000
REFINER_TIME_STEPS = 100000

ABSTRACTION_PERCENTAGE = 0.0
WIZARD_COEFFICIENT = 2

PERFORM_ABSTRACTION = True
COMPRESS_PLAYER_2 = True

SAVE_REGRETS_TO_JSON = False

VISUALIZE_PLOT = False

PERFORM_REFINEMENT = False

SAVE_STRATEGY_TO_FILE = True

PRINT_BOTH_STRATEGIES = True
