FILE_NAME = 'Leduc_A.txt'
SOLVER_TIME_STEPS = 10000
REFINER_TIME_STEPS = 1000

ABSTRACTION_PERCENTAGE = 1.0
WIZARD_COEFFICIENT = 2
PERFORM_ABSTRACTION = True
COMPRESS_PLAYER_2 = True
PERFORM_REFINEMENT = True
PRINT_BOTH_STRATEGIES = True
